apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - uses: docker://alpine/git:latest
        name: Add workspace
        run: |
          git config --global --add safe.directory /cloudbees/workspace
      - uses: cloudbees-io/checkout@v1
        name: checkout
      - uses: docker://golang:1.20
        name: Build Go app
        run: |
          go build -v ./...
      - uses: docker://golang:1.20
        name: Run tests
        run: |
          go test -v ./...
      - uses: GHA-TalaveraCloudbees
        name: Run GHA
  deploy:
    environment: devJT
    steps:
      - uses: docker://golang:1.20
        name: Pretend to deploy
        run: echo “Pretending to deploy to namespace ${{vars.DEPLOY_NAMESPACE}} using
          token ${{secrets.DEPLOY_TOKEN}}”
        shell: sh
    needs: build
